version: '3'
services:
  service1:
    image: label-service
    deploy:
      resources:
        reservations:
          memory: 16M
        limits:
          memory: 64M
  service2:
    extends:
      service: service1
  service3:
    extends:
      service: service1
  service4:
    extends:
      service: service1
  service5:
    extends:
      service: service1
  service6:
    extends:
      service: service1
  service7:
    extends:
      service: service1
  service8:
    extends:
      service: service1
  loadbalancer:
    build: load-balancer
    depends_on:
      - service1
      - service2
      - service3
      - service4
      - service5
      - service6
      - service7
      - service8
    ports:
      - 8090:80
