image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cd build-tools && make
      cd ../label-service && make

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-maven
    - vscjava.vscode-java-test
